import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import {
  assetNameFor,
  compareSemver,
  stripV,
} from "../src/update/version.ts";
import {
  parseChecksumFromBody,
  parseChecksumsFile,
} from "../src/update/releases.ts";

let tmpHshHome: string;
const realHshHome = process.env.HSH_HOME;

beforeEach(() => {
  tmpHshHome = mkdtempSync(join(tmpdir(), "hsh-update-"));
  process.env.HSH_HOME = tmpHshHome;
});

afterEach(() => {
  if (realHshHome !== undefined) process.env.HSH_HOME = realHshHome;
  else delete process.env.HSH_HOME;
  rmSync(tmpHshHome, { recursive: true, force: true });
});

describe("stripV", () => {
  test.each([
    ["v1.2.3", "1.2.3"],
    ["1.2.3", "1.2.3"],
    ["v0.0.1", "0.0.1"],
    ["", ""],
  ])("stripV(%p) → %p", (input, expected) => {
    expect(stripV(input)).toBe(expected);
  });
});

describe("compareSemver", () => {
  test("identical versions are equal", () => {
    expect(compareSemver("1.2.3", "1.2.3")).toBe(0);
    expect(compareSemver("v1.2.3", "1.2.3")).toBe(0);
  });

  test.each([
    ["1.2.4", "1.2.3"],
    ["1.3.0", "1.2.99"],
    ["2.0.0", "1.99.99"],
    ["v1.2.3", "v1.2.2"],
  ])("%p > %p", (a, b) => {
    expect(compareSemver(a, b)).toBe(1);
    expect(compareSemver(b, a)).toBe(-1);
  });

  test("pre-release versions sort BEFORE the release", () => {
    expect(compareSemver("1.2.3", "1.2.3-rc.1")).toBe(1);
    expect(compareSemver("1.2.3-rc.1", "1.2.3")).toBe(-1);
    expect(compareSemver("1.2.3-rc.1", "1.2.3-rc.2")).toBe(-1);
  });

  test("build metadata is ignored", () => {
    expect(compareSemver("1.2.3+build.1", "1.2.3+build.2")).toBe(0);
    expect(compareSemver("1.2.3+a", "1.2.3")).toBe(0);
  });

  test("missing patch coerces to 0", () => {
    expect(compareSemver("1.2", "1.2.0")).toBe(0);
    expect(compareSemver("1.2", "1.2.1")).toBe(-1);
  });
});

describe("assetNameFor", () => {
  test.each([
    ["linux", "x64", "hsh-linux-x64"],
    ["linux", "arm64", "hsh-linux-arm64"],
    ["darwin", "x64", "hsh-darwin-x64"],
    ["darwin", "arm64", "hsh-darwin-arm64"],
    ["win32", "x64", "hsh-windows-x64.exe"],
  ] as const)("%p/%p → %p", (platform, arch, expected) => {
    expect(assetNameFor(platform as NodeJS.Platform, arch as NodeJS.Architecture)).toBe(expected);
  });

  test.each([
    ["linux", "ia32"],
    ["darwin", "ia32"],
    ["win32", "arm64"],
    ["freebsd", "x64"],
  ] as const)("%p/%p → null (unsupported)", (platform, arch) => {
    expect(assetNameFor(platform as NodeJS.Platform, arch as NodeJS.Architecture)).toBeNull();
  });
});

describe("parseChecksumsFile", () => {
  test("plain sha256sum format with two-space separator", () => {
    const content =
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789  hsh-linux-x64\n" +
      "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210  hsh-darwin-arm64\n";
    expect(parseChecksumsFile(content, "hsh-linux-x64")).toBe(
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
    );
    expect(parseChecksumsFile(content, "hsh-darwin-arm64")).toBe(
      "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210",
    );
  });

  test("binary-mode prefix (asterisk before filename)", () => {
    const content =
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789 *hsh-linux-x64\n";
    expect(parseChecksumsFile(content, "hsh-linux-x64")).toBe(
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
    );
  });

  test("ignores blank lines and comments", () => {
    const content =
      "# Hash file generated by sha256sum\n" +
      "\n" +
      "  \n" +
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789  hsh-linux-x64\n";
    expect(parseChecksumsFile(content, "hsh-linux-x64")).toBe(
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
    );
  });

  test("returns null when filename is absent", () => {
    const content =
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789  other-file\n";
    expect(parseChecksumsFile(content, "hsh-linux-x64")).toBeNull();
  });

  test("normalizes hex to lowercase", () => {
    const content =
      "ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789  hsh-linux-x64\n";
    expect(parseChecksumsFile(content, "hsh-linux-x64")).toBe(
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
    );
  });
});

describe("parseChecksumFromBody", () => {
  test("inline checksum line in markdown body", () => {
    const body =
      "## Release notes\n" +
      "\n" +
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789 hsh-linux-x64\n" +
      "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210 hsh-darwin-arm64\n";
    expect(parseChecksumFromBody(body, "hsh-linux-x64")).toBe(
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
    );
  });

  test("checksum inside a code fence", () => {
    const body =
      "Checksums:\n" +
      "```\n" +
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789  hsh-linux-x64\n" +
      "```\n";
    expect(parseChecksumFromBody(body, "hsh-linux-x64")).toBe(
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
    );
  });

  test("dot in asset name (windows .exe) is escaped correctly", () => {
    const body =
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789 hsh-windows-x64.exe\n";
    expect(parseChecksumFromBody(body, "hsh-windows-x64.exe")).toBe(
      "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
    );
  });

  test("returns null when no matching line", () => {
    const body = "No checksums published in this release.\n";
    expect(parseChecksumFromBody(body, "hsh-linux-x64")).toBeNull();
  });
});
