import { Command } from "commander";
import { getWrappedCommands } from "../plugins/registry.ts";

export const shellInitCommand = new Command("shell-init")
  .description("Output shell integration code (add to .bashrc/.zshrc with eval)")
  .option("--shell <shell>", "Shell type (bash, zsh, fish)")
  .action((opts: { shell?: string }) => {
    const shell = opts.shell ?? detectShell();
    const commands = getWrappedCommands();

    if (shell === "fish") {
      console.log(generateFish(commands));
    } else {
      console.log(generatePosix(commands));
    }
  });

function detectShell(): string {
  const shell = process.env.SHELL ?? "";
  if (shell.includes("fish")) return "fish";
  if (shell.includes("zsh")) return "zsh";
  return "bash";
}

function generatePosix(commands: { command: string; plugin: string }[]): string {
  const lines: string[] = [
    "# Hoop Shell Plugins - generated by hsh",
    "# Add to your shell profile: eval \"$(hsh shell-init)\"",
    "",
  ];

  for (const { command, plugin } of commands) {
    lines.push(`__hsh_${plugin}() {`);
    lines.push(`  command hsh plugin run ${plugin} -- "$@"`);
    lines.push(`  return $?`);
    lines.push(`}`);
    lines.push(`alias ${command}='__hsh_${plugin}'`);
    lines.push("");
  }

  return lines.join("\n");
}

function generateFish(commands: { command: string; plugin: string }[]): string {
  const lines: string[] = [
    "# Hoop Shell Plugins - generated by hsh",
    "# Add to your config.fish: hsh shell-init --shell fish | source",
    "",
  ];

  for (const { command, plugin } of commands) {
    lines.push(`function ${command}`);
    lines.push(`  command hsh plugin run ${plugin} -- $argv`);
    lines.push(`end`);
    lines.push("");
  }

  return lines.join("\n");
}
