import { Command } from "commander";
import { getWrappedCommands } from "../plugins/registry.ts";

export const shellInitCommand = new Command("shell-init")
  .description("Output shell integration code (add to .bashrc/.zshrc with eval)")
  .option("--shell <shell>", "Shell type (bash, zsh, fish)")
  .action((opts: { shell?: string }) => {
    const shell = opts.shell ?? detectShell();
    const commands = getWrappedCommands();

    if (shell === "fish") {
      console.log(generateFish(commands));
    } else {
      console.log(generatePosix(commands));
    }
  });

function detectShell(): string {
  const shell = process.env.SHELL ?? "";
  if (shell.includes("fish")) return "fish";
  if (shell.includes("zsh")) return "zsh";
  return "bash";
}

function generatePosix(commands: { command: string; plugin: string }[]): string {
  const lines: string[] = [
    "# Hoop Shell Plugins - generated by hsh",
    '# Add to your shell profile: eval "$(hsh shell-init)"',
    "",
  ];

  for (const { command, plugin } of commands) {
    // Shell function wrapping the native command
    lines.push(`${command}() {`);
    lines.push(`  command hsh plugin run ${plugin} -- "$@"`);
    lines.push(`  return $?`);
    lines.push(`}`);
    lines.push("");
  }

  // Export GIT_SSH_COMMAND so git push/pull/clone also goes through hsh
  // rsync -e ssh and scp also respect this when using ProxyCommand
  lines.push("# Make tools that invoke ssh internally (git, rsync, scp) use hsh");
  lines.push('export GIT_SSH_COMMAND="hsh plugin run ssh --"');
  lines.push('export RSYNC_RSH="hsh plugin run ssh --"');
  lines.push("");

  return lines.join("\n");
}

function generateFish(commands: { command: string; plugin: string }[]): string {
  const lines: string[] = [
    "# Hoop Shell Plugins - generated by hsh",
    "# Add to your config.fish: hsh shell-init --shell fish | source",
    "",
  ];

  for (const { command, plugin } of commands) {
    lines.push(`function ${command}`);
    lines.push(`  command hsh plugin run ${plugin} -- $argv`);
    lines.push(`end`);
    lines.push("");
  }

  lines.push("# Make tools that invoke ssh internally (git, rsync, scp) use hsh");
  lines.push('set -gx GIT_SSH_COMMAND "hsh plugin run ssh --"');
  lines.push('set -gx RSYNC_RSH "hsh plugin run ssh --"');
  lines.push("");

  return lines.join("\n");
}
