/**
 * scripts/lib/daemon-download.ts — build-time download + verification
 * of the bundled `hsh-tunneld` binary and its install scripts.
 *
 * # Contract
 *
 * Given a `version` string (either "latest" or a concrete tag like
 * "v0.0.42") and a target tuple (goos + goarch), produce a directory
 * on disk containing exactly three files, all verified against the
 * SHA256SUMS published by the hoop release:
 *
 *   <stagingDir>/hsh-tunneld[.exe]
 *   <stagingDir>/install.sh
 *   <stagingDir>/uninstall.sh
 *
 * The caller (scripts/build.ts) treats the staging directory as the
 * payload that goes into the per-target archive.
 *
 * # Failure modes
 *
 * Every failure is a hard abort with an actionable message:
 *
 *   - Cannot resolve "latest" -> the GitHub API URL is included so
 *     the user can curl it manually and see why.
 *   - Asset not found in release -> we list what assets *are* there
 *     so a typo in the version pin gets spotted immediately.
 *   - SHA mismatch -> we print the expected vs got hashes and the
 *     URL, then exit. We do NOT keep the partial file.
 *
 * The "fall back to a sibling binary in /tmp" option was deliberately
 * rejected (see the question/answer thread for RD-227): it would make
 * the build silently ship the wrong binary in CI where nobody is
 * watching the warnings.
 *
 * # Cache
 *
 * Downloads are cached under <cacheRoot>/<version>/<filename>. A
 * subsequent build with the same version reuses the cache so the
 * 5-target matrix only pays the network cost once per daemon
 * version. The cache is keyed by the *resolved* version (post
 * "latest" -> "v0.0.X"), so changing only the resolution date does
 * not invalidate already-downloaded files.
 *
 * Cache validation is by SHA256, not by file presence. A cached
 * file whose hash drifted (corrupt disk, manual edit) is treated as
 * a miss and re-downloaded.
 */

import { createHash } from "crypto";
import { existsSync } from "fs";
import { chmod, mkdir, readFile, rename, writeFile } from "fs/promises";
import { dirname, join } from "path";

/**
 * GitHub release repo we pull the daemon from. Hard-coded because
 * cross-repo bundles need an explicit, audit-able trust root.
 */
const RELEASE_REPO = "hoophq/hoop";

/**
 * Public hosts. Spelled out as constants so a corporate proxy can
 * patch them in a single place via fork.
 */
const GITHUB_API = "https://api.github.com";
const GITHUB_DOWNLOAD = "https://github.com";

/**
 * Target tuple describing which daemon asset to fetch. The `goos`
 * and `goarch` strings match Go's runtime.GOOS/GOARCH naming so the
 * hoop release filename (`hsh-tunneld-<goos>-<goarch>[.exe]`) maps
 * directly without translation.
 */
export interface Target {
  /** Go-style operating system: "linux" | "darwin" | "windows". */
  goos: "linux" | "darwin" | "windows";
  /** Go-style architecture: "amd64" | "arm64". */
  goarch: "amd64" | "arm64";
}

/**
 * Returns the conventional release filename for a daemon binary on
 * the given target. Mirrors the hoop Makefile's HSH_TUNNELD_EXE
 * variable so a drift between repos is caught by build failure.
 */
export function daemonAssetName(t: Target): string {
  const suffix = t.goos === "windows" ? ".exe" : "";
  return `hsh-tunneld-${t.goos}-${t.goarch}${suffix}`;
}

/**
 * Filename the install/uninstall scripts use in the release. The
 * hoop Makefile's stage-release-scripts target uploads them under
 * these exact names; we keep them as constants so a rename on either
 * side fails loudly.
 */
export const INSTALL_SCRIPT_NAME = "install.sh";
export const UNINSTALL_SCRIPT_NAME = "uninstall.sh";

/**
 * Filename of the checksum manifest in the release. Generated by
 * `make build-release-checksums` on the hoop side. Every file we
 * download is verified against an entry in this manifest.
 */
const SHA256SUMS_NAME = "SHA256SUMS";

/**
 * Options for the resolver/downloader.
 */
export interface DownloadOptions {
  /**
   * The version we want. Either "latest" or a concrete tag like
   * "v0.0.42". Resolution happens once per build, not per target.
   */
  version: string;
  /**
   * Directory under which per-version subdirectories are kept. The
   * call site (scripts/build.ts) uses `dist/.daemon-cache/`.
   */
  cacheRoot: string;
  /**
   * Optional log sink. Defaults to console.log. Provided for tests.
   */
  log?: (msg: string) => void;
}

/**
 * Resolved version + manifest cache. resolveVersion fills this once
 * per build; per-target downloads consume it.
 */
export interface ResolvedRelease {
  /** Concrete tag, e.g. "v0.0.42". Never "latest" here. */
  version: string;
  /** Parsed contents of SHA256SUMS: filename -> hex sha256. */
  checksums: Map<string, string>;
  /** Directory under cacheRoot where downloads land. */
  cacheDir: string;
}

/**
 * Resolve "latest" (or pass through a pinned tag) and download
 * SHA256SUMS. Returns the data both downstream callers need
 * (concrete tag + checksum map + cache directory).
 *
 * Fails hard with an actionable message on any error. The error
 * messages include the URL that failed so the user can curl it
 * manually as the first triage step.
 */
export async function resolveRelease(opts: DownloadOptions): Promise<ResolvedRelease> {
  const log = opts.log ?? ((m) => console.log(m));

  // 1. Resolve symbolic "latest" -> concrete tag via the GitHub API.
  //
  // We could skip the API call for non-"latest" values and just trust
  // the user-supplied tag. We do it anyway for non-latest too —
  // calling /releases/tags/<tag> verifies the tag exists before we
  // start downloading multiple assets, which fails faster than a
  // 404 on the asset URL itself.
  let version = opts.version.trim();
  if (version.toLowerCase() === "latest") {
    log("Resolving daemon version: 'latest' -> ?");
    const apiUrl = `${GITHUB_API}/repos/${RELEASE_REPO}/releases/latest`;
    const apiResp = await fetch(apiUrl, githubApiHeaders());
    if (!apiResp.ok) {
      throw new Error(
        `Failed to resolve 'latest' from ${apiUrl}: HTTP ${apiResp.status} ${apiResp.statusText}. ` +
          `Set HSH_TUNNELD_VERSION=v<X.Y.Z> to pin a specific version instead.`,
      );
    }
    const body = (await apiResp.json()) as { tag_name?: string };
    if (!body.tag_name) {
      throw new Error(
        `GitHub API at ${apiUrl} returned a release with no tag_name. ` +
          `Body: ${JSON.stringify(body).slice(0, 200)}`,
      );
    }
    version = body.tag_name;
    log(`Resolved daemon version: 'latest' -> ${version}`);
  } else {
    // Non-latest: verify the tag exists. Use the tag-lookup endpoint
    // because it's the cheapest 404 we can elicit.
    const apiUrl = `${GITHUB_API}/repos/${RELEASE_REPO}/releases/tags/${version}`;
    const apiResp = await fetch(apiUrl, githubApiHeaders());
    if (!apiResp.ok) {
      throw new Error(
        `Pinned daemon version ${version} does not exist as a release on ${RELEASE_REPO}: ` +
          `HTTP ${apiResp.status} from ${apiUrl}. Check the tag and try again.`,
      );
    }
    log(`Using pinned daemon version: ${version}`);
  }

  const cacheDir = join(opts.cacheRoot, version);
  await mkdir(cacheDir, { recursive: true });

  // 2. Download (or load from cache) the SHA256SUMS manifest. We always
  // re-download SHA256SUMS itself even if cached, because the cost is
  // ~1 KB and the manifest is the trust root for everything else —
  // skipping its freshness would defeat the purpose of caching.
  const checksumPath = join(cacheDir, SHA256SUMS_NAME);
  const checksumUrl = `${GITHUB_DOWNLOAD}/${RELEASE_REPO}/releases/download/${version}/${SHA256SUMS_NAME}`;
  log(`Downloading ${SHA256SUMS_NAME} from ${checksumUrl}`);
  const checksumResp = await fetch(checksumUrl);
  if (!checksumResp.ok) {
    throw new Error(
      `Failed to fetch ${SHA256SUMS_NAME} for ${version}: HTTP ${checksumResp.status} from ${checksumUrl}. ` +
        `The release tag may not have an attached SHA256SUMS file (older releases?). ` +
        `Pin a more recent version via HSH_TUNNELD_VERSION.`,
    );
  }
  const checksumBody = await checksumResp.text();
  await writeFile(checksumPath, checksumBody);

  const checksums = parseSha256sums(checksumBody);
  if (checksums.size === 0) {
    throw new Error(
      `Parsed empty checksum map from ${checksumUrl}. Body was:\n${checksumBody.slice(0, 400)}`,
    );
  }

  // 3. Sanity check: the manifest must contain both install scripts.
  // If they're missing the user is targeting an older release that
  // doesn't have the install scripts attached — pin to a newer tag.
  for (const required of [INSTALL_SCRIPT_NAME, UNINSTALL_SCRIPT_NAME]) {
    if (!checksums.has(required)) {
      throw new Error(
        `Release ${version} does not include ${required} in SHA256SUMS. ` +
          `This release predates RD-226 (install scripts as release assets). ` +
          `Pin a newer HSH_TUNNELD_VERSION or accept "latest".`,
      );
    }
  }

  return { version, checksums, cacheDir };
}

/**
 * Download a single asset from a resolved release and verify its
 * checksum. Returns the local path. Uses the cache when the file is
 * already present and its hash matches the manifest.
 *
 * The download lands in <cacheDir>/<filename>; the caller can move
 * or copy from there into the per-target staging directory.
 */
export async function downloadAsset(
  rel: ResolvedRelease,
  filename: string,
  opts: { log?: (msg: string) => void } = {},
): Promise<string> {
  const log = opts.log ?? ((m) => console.log(m));
  const expected = rel.checksums.get(filename);
  if (!expected) {
    const known = [...rel.checksums.keys()].sort().join(", ");
    throw new Error(
      `No checksum entry for ${filename} in SHA256SUMS for ${rel.version}. ` +
        `Available assets: ${known}`,
    );
  }

  const dest = join(rel.cacheDir, filename);

  // Cache hit?
  if (existsSync(dest)) {
    const got = await sha256OfFile(dest);
    if (got === expected) {
      log(`  ${filename}  (cache hit)`);
      return dest;
    }
    log(`  ${filename}  (cache stale, sha mismatch -> redownload)`);
  }

  const url = `${GITHUB_DOWNLOAD}/${RELEASE_REPO}/releases/download/${rel.version}/${filename}`;
  log(`  ${filename}  -> ${url}`);
  const resp = await fetch(url);
  if (!resp.ok) {
    const known = [...rel.checksums.keys()].sort().join(", ");
    throw new Error(
      `Failed to download ${filename} for ${rel.version}: HTTP ${resp.status} from ${url}. ` +
        `Available assets: ${known}`,
    );
  }
  const body = new Uint8Array(await resp.arrayBuffer());

  // Verify *before* publishing to the cache location, so a failed
  // verify never leaves a "good"-looking file on disk.
  const got = hexSha256(body);
  if (got !== expected) {
    throw new Error(
      `SHA256 mismatch for ${filename} from ${rel.version}.\n` +
        `  expected: ${expected}\n` +
        `  got:      ${got}\n` +
        `  url:      ${url}\n` +
        `Refusing to publish a tampered download. If you believe the upstream is correct, ` +
        `delete the cache directory and retry; if the mismatch persists, the release artifact ` +
        `itself is corrupt and needs to be re-uploaded.`,
    );
  }

  // Atomic publish: write to a .tmp sibling, then rename. Two parallel
  // calls for the same filename (shouldn't happen given resolveRelease
  // is called once, but defence in depth) end up with one winner and
  // one harmless ENOENT on the loser's rename.
  const tmp = `${dest}.tmp.${process.pid}`;
  await mkdir(dirname(tmp), { recursive: true });
  await writeFile(tmp, body);
  await rename(tmp, dest);
  return dest;
}

/**
 * Convenience: download all three artifacts a per-target archive
 * needs (daemon binary + both scripts). Returns absolute paths in
 * the same order the caller can pass to a staging step.
 */
export async function downloadTargetAssets(
  rel: ResolvedRelease,
  target: Target,
  opts: { log?: (msg: string) => void } = {},
): Promise<{ daemon: string; installScript: string; uninstallScript: string }> {
  const daemon = await downloadAsset(rel, daemonAssetName(target), opts);
  const installScript = await downloadAsset(rel, INSTALL_SCRIPT_NAME, opts);
  const uninstallScript = await downloadAsset(rel, UNINSTALL_SCRIPT_NAME, opts);
  // Daemons + scripts come from `gh release upload` which doesn't
  // preserve exec bits across the boundary. Restore them now so the
  // staged tree is ready to tar.
  await chmod(daemon, 0o755);
  await chmod(installScript, 0o755);
  await chmod(uninstallScript, 0o755);
  return { daemon, installScript, uninstallScript };
}

// --- internals ---

/**
 * Build the headers we send to api.github.com. Includes the
 * GITHUB_TOKEN if present so CI builds get the authenticated 5000 req/h
 * rate budget instead of the anonymous 60 req/h. Local builds work
 * unauthenticated because a single bun-run-build at 1 API call is far
 * below the anonymous quota.
 */
function githubApiHeaders(): RequestInit {
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  const headers: Record<string, string> = {
    Accept: "application/vnd.github+json",
    "User-Agent": "hsh-bundler",
    "X-GitHub-Api-Version": "2022-11-28",
  };
  if (token) {
    headers["Authorization"] = `Bearer ${token}`;
  }
  return { headers };
}

/**
 * Parse a `sha256sum` style file. Each line is `<hex>  <filename>`.
 * Tolerates leading `*` (binary mode marker) before the filename
 * even though we don't produce those ourselves — defence in depth.
 *
 * Exported only for unit tests; consumers should rely on
 * resolveRelease, which calls this internally on the SHA256SUMS
 * payload it downloads.
 */
export function parseSha256sums(body: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const rawLine of body.split("\n")) {
    const line = rawLine.trim();
    if (line === "" || line.startsWith("#")) continue;
    // The canonical sha256sum format is `<hex><space><binary-mode-or-space><filename>`.
    // Split on whitespace and take the first two non-empty fragments.
    const parts = line.split(/\s+/).filter((s) => s.length > 0);
    if (parts.length !== 2) continue;
    const [hex, fileWithMaybeStar] = parts;
    // Drop the `*` binary-mode marker if present.
    const file = fileWithMaybeStar.startsWith("*") ? fileWithMaybeStar.slice(1) : fileWithMaybeStar;
    out.set(file, hex.toLowerCase());
  }
  return out;
}

/**
 * Compute the lowercase-hex sha256 of a Uint8Array.
 */
function hexSha256(data: Uint8Array): string {
  const h = createHash("sha256");
  h.update(data);
  return h.digest("hex");
}

/**
 * Compute the lowercase-hex sha256 of a file on disk.
 */
async function sha256OfFile(path: string): Promise<string> {
  const buf = await readFile(path);
  return hexSha256(buf);
}
